file-version: 1
vendor: OneLang
name: Json
version: 0.1
includes:
  - langs/csharp.yaml
  - langs/go.yaml
  - langs/java.yaml
  - langs/javascript.yaml
  - langs/php.yaml
  - langs/python.yaml
  - langs/ruby.yaml
  - langs/swift.yaml
  - langs/typescript.yaml
languages:
  java:
    package-dir: json
    native-src-dir: Java/src
    native-dependencies:
      - { name: com.google.code.gson:gson, version: 2.8.6 }
    generator-plugins: [Java/JsToJava.yaml]
  csharp:
    native-src-dir: CSharp/src
    native-dependencies:
      - { name: Newtonsoft.Json, version: 12.0.3 }
  php:
    generator-plugins: [PHP/JsToPhp.yaml]
